baseURL = 'https://andriesfc.github.io'
languageCode = 'en-us'
title = "A mind is such a terrible thing to waste"
paginate = 1
Copyright = "© Andries 2021"
canonifyurls = true
theme="casper"

[params]
cover="images/cover-va-capetown.jpg"
logo="images/myself_r.png"
description="My personal space on the interwebs"
author="Andries"
githubName="andriesfc"
instagramName="andries.fc"
linkedinName="andriesp"
hideHugoSupport = false
authorlocation="Cape Town"

[[menu.main]]
name = "Home"
weight = 100
identifier="home"
pre="<br />"
url="/"

[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/posts"
weight = 40

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"